api/urls.py
from . import views
from rest_framework.routers import SimpleRouter
from django.urls import path, include
# address haye apilication api
urlpatterns = [
    path("get_home/<slug:password>", views.getHome.as_view()),
    path("post_status_to_home/", views.postStatusToHome.as_view()),
    path("create_home/", views.CreateHome.as_view()),
    path("get_physics_order/", views.getPhysicsOrder.as_view()),
]

blog/urls.py
from . import views
from django.urls import path, include
# address haye apilication blog
app_name = 'blog'
urlpatterns = [
    path("", views.ArticleListView.as_view() , name="list"),
    path("<slug:slug>", views.ArticleDetailView.as_view() , name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as accountViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path("accounts/profile/", accountViews.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = "home"
# address haye applicatione home
urlpatterns = [
    path("create_home/", views.CreateHomeView.as_view(), name="send"),
    path("create_device/", views.send, name="send_device"),
    path("post_device/", views.post_device, name="post_device"),
    # path("post_device/", views.GUIOrderClassModelView.as_view(), name="post_device"),
    path("list_device/", views.DeviceListView.as_view(), name="list_device"),
    path("", views.HomeView.as_view(), name="index"),
    path("guide/", views.GuideView.as_view(), name="guide"),
    path("about_me/", views.AboutMe.as_view(), name="about_me"),
    path("faq/", views.CommentListView.as_view() , name="faq"),
    path("listPacks/", views.listPackage.as_view() , name="listpacks"),
    path("sendPacks/", views.sendPackage , name="packs"),
]

shop/urls.py
from . import views
from django.urls import path, include
# address haye apilication
app_name = 'shop'
urlpatterns = [
    path("", views.ObjectListView.as_view() , name="list"),
    path("<int:pk>/", views.ObjectDetailView.as_view() , name="detail"),
    path("send/", views.AddCartFormView.as_view() , name="send"),
]

shop/models.py
from django.db import models
from account.models import User

# models haye kala ha
class Object(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='images/obj/')
    thumbnail2 = models.ImageField(upload_to='images/obj/')
    color = models.CharField(max_length=100)
    size = models.CharField(max_length=255)
    mark = models.CharField(max_length=255)
    masraf = models.IntegerField()
    price = models.FloatField()
    category = models.CharField(max_length=255)
    offprice = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class cart_obj(models.Model):

    CART_OBJ_COLOR_CHOICES = (
        ("black", "black"),
        ("white", "white"),
        ("red", "red"),
        ("blue", "blue"),
        ("green", "green"),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    obj = models.ManyToManyField(Object)
    color = models.CharField(max_length=10, choices=CART_OBJ_COLOR_CHOICES)
    count = models.IntegerField()

    def __str__(self):
        return self.user.username

shop/forms.py
from django import forms
from . import models
# class form haye site
class CartAddObjsForm(forms.Form):
    class Meta:
        model = models.cart_obj
        fields = "__all__"

shop/views.py
from typing import Any, Dict
from django.http import HttpResponse
from django.shortcuts import render
from . import models
from . import forms
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView

# class list kardan kala ha
class ObjectListView(ListView):
    model = models.Object
    context_object_name = 'objects'
    template_name = 'objects/index.html'
    queryset = models.Object.objects.all().order_by('masraf')

    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_new'] = models.Object.objects.all().order_by('-created', '-updated')
        context['objects'] = models.Object.objects.all().order_by('masraf')
        return context

# class joseiate kala ye
class ObjectDetailView(DetailView):
    model = models.Object
    context_object_name = 'object'
    template_name = 'objects/detail.html'

    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class AddCartFormView(FormView):
    template_name = 'objects/send.html'
    form_class = forms.CartAddObjsForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.user = self.request.user.id
        form.instance.obj = models.Object.objects.all().filter(id=self.request.GET['obj']).first()
        form.save()
        return super().form_valid(form)
    def form_invalid(self, form):
        return HttpResponse(form.errors)

shop/templates/objects/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Smart House</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">
    {% load static %}
    <link href="img/favicon.ico" rel="icon">

    <!-- font haye google -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- file haye css -->
    <link href="{% static 'shop/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'shop/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font.css' %}" rel="stylesheet">
</head>

<body style="font-family: 'Vazir';">
    <!-- navbare site  -->
    <div class="container-fluid">
        <div style="background-color: white !important; margin-left: 73.5%;" class="row bg-secondary py-2 px-xl-5">
            <div style="color: #0B5ED7 !important;" class="d-inline-flex align-items-center">
                <a style="color: #0B5ED7 !important;" class="text-dark" href="{% url 'blog:list' %}">بلاگ</a>
                <span style="color: #0B5ED7 !important;" class="text-muted px-2">/</span>
                <a style="color: #0B5ED7 !important;" class="text-dark" href="{% url 'home:guide' %}">راهنما</a>
                <span style="color: #0B5ED7 !important;" class="text-muted px-2">/</span>
                <a style="color: #0B5ED7 !important;" class="text-dark" href="{% url 'home:index' %}">خانه</a>
                <span style="color: #0B5ED7 !important;" class="text-muted px-2">/</span>
                <a style="color: #0B5ED7 !important;" class="text-dark" href="{% url 'home:about_me' %}">درباره‌من</a>
                <span style="color: #0B5ED7 !important;" class="text-muted px-2">/</span>
                <a style="color: #6c757d !important;" class="text-dark">فروشگاه</a>
                <span style="color: #0B5ED7 !important;" class="text-muted px-2">/</span>
                <a style="color: #0B5ED7 !important;" class="text-dark" href="{% url 'home:faq' %}">سوالات‌پر‌تکرار</a>
            </div>
        </div>
        </div>
        <div style="direction: rtl;" class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold">فروشگاه<span style="color: #31d2f2 !important;" class="text-primary font-weight-bold border px-3 mr-1">خانه‌هوشمند</span></h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="جست و جو در محصولات">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i style="color: #31d2f2 !important;" class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i style="color: #31d2f2 !important;" class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="" class="btn border">
                    <i style="color: #31d2f2 !important;" class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">0</span>
                </a>
            </div>
        </div>
    </div>

    <!-- headere safhe -->
    <div style="background-color: #bcf5ff !important;" class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">جزئیات محصول</h1>
            <div class="d-inline-flex">
                <p style="color: #0B5ED7 !important;" class="m-0"><a href="{% url 'shop:list' %}">فروشگاه</a></p>
                <p class="m-0 px-2">/</p>
                <p class="m-0">جزئیات محصول</p>
            </div>
        </div>
    </div>
    <!-- joseyate kala -->
    <div class="container-fluid py-5">
        <div style="direction: rtl;" class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="{{ object.thumbnail.url }}" alt="Image">
                        </div>
                        <div class="carousel-item">
                            <img class="w-100 h-100" src="{{ object.thumbnail2.url }}" alt="Image">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>
            </div>

            <div style="direction: rtl; text-align: right;" class="col-lg-7 pb-5">
                <h3 class="font-weight-semi-bold">{{ object.title }}</h3>
                <div class="d-flex mb-3">
                    <div style="color: #31d2f2 !important;" class="text-primary mr-2">
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                    </div>
                </div>
                <p style="color: white !important; background-color: #31d2f2 !important;" class=" badge bg-primary pt-1">دسته‌بندی : {{ object.category }}</p>
                <h3>${{ object.price }}</h3><h3 class="text-muted ml-2"><del>${{ object.offprice }}</del></h3>
                <p class="mb-4">{{ object.description | slice:":70" }}...</p>
                <form action="{% url 'shop:send' %}">{% csrf_token %}
                    <div class="d-flex mb-4">
                            <p style="margin-top: .57%;">رنگ‌:</p><select class="custom-control custom-select custom-control-inline" name="color" id="color">
                                <option value="black">سیاه</option>
                                <option value="white">سفید</option>
                                <option value="red">قرمز</option>
                                <option value="blue">آبی</option>
                                <option value="green">سبز</option>
                            </select>
                            <input type="hidden", name="obj" value="{{ object.id }}">
                    </div>
                    <div class="d-flex align-items-center mb-4 pt-2">
                        <div class="input-group quantity mr-3" style="width: 130px;">
                            <div class="input-group-btn">
                                <button style="background-color: #31d2f2 !important; border-color: #31d2f2 !important;" type="button" class="btn btn-primary btn-minus" >
                                <i class="fa fa-minus"></i>
                                </button>
                            </div>
                            <input style="background-color: #bcf5ff !important;" name="count" type="text" class="form-control bg-secondary text-center" value="1">
                            <div class="input-group-btn">
                                <button style="background-color: #31d2f2 !important; border-color: #31d2f2 !important;" type="button" class="btn btn-primary btn-plus">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <button style="background-color: #31d2f2 !important; border-color: #31d2f2 !important;" type="submit" class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> اضافه‌به‌سبد‌خرید</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="nav nav-tabs justify-content-center border-secondary mb-4">
                    <a class="nav-item nav-link active" data-toggle="tab" href="#tab-pane-1">توضیحات</a>
                </div>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="tab-pane-1">
                        <h4 style="text-align: right;" class="mb-3">توضیحات محصول</h4>
                        <p style="direction: rtl; text-align: right;">{{ object.description }}</p><br><br>
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">مشخصات</th>
                                <th scope="col">مقدار</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <th scope="row">1</th>
                                <td>رنگ:</td>
                                <td>{{ object.color }}</td>
                              </tr>
                              <tr>
                                <th scope="row">2</th>
                                <td>اندازه:</td>
                                <td>{{ object.size }}</td>
                              </tr>
                              <tr>
                                <th scope="row">3</th>
                                <td>برند:</td>
                                <td>{{ object.mark }}</td>
                              </tr>
                              <tr>
                                <th scope="row">4</th>
                                <td>مصرف:</td>
                                <td>کیلووات {{ object.masraf }}</td>
                              </tr>
                            </tbody>
                          </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a style="background-color: #31d2f2 !important; border-color: #31d2f2 !important;" href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- file haye javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'shop/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'shop/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'shop/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'shop/mail/contact.js' %}"></script>
    <script src="{% static 'shop/js/main.js' %}"></script>
</body>
{% include 'home/footer copy.html' %}
</html>