api/urls.py
from . import views
from rest_framework.routers import SimpleRouter
from django.urls import path, include
# address haye apilication api
urlpatterns = [
    path("get_home/<slug:password>", views.getHome.as_view()),
    path("post_status_to_home/", views.postStatusToHome.as_view()),
    path("create_home/", views.CreateHome.as_view()),
    path("get_physics_order/", views.getPhysicsOrder.as_view()),
]

blog/urls.py
from . import views
from django.urls import path, include
# address haye apilication blog
app_name = 'blog'
urlpatterns = [
    path("", views.ArticleListView.as_view() , name="list"),
    path("<slug:slug>", views.ArticleDetailView.as_view() , name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as accountViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path("accounts/profile/", accountViews.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = "home"
# address haye applicatione home
urlpatterns = [
    path("create_home/", views.CreateHomeView.as_view(), name="send"),
    path("create_device/", views.send, name="send_device"),
    path("post_device/", views.post_device, name="post_device"),
    # path("post_device/", views.GUIOrderClassModelView.as_view(), name="post_device"),
    path("list_device/", views.DeviceListView.as_view(), name="list_device"),
    path("", views.HomeView.as_view(), name="index"),
    path("guide/", views.GuideView.as_view(), name="guide"),
    path("about_me/", views.AboutMe.as_view(), name="about_me"),
    path("faq/", views.CommentListView.as_view() , name="faq"),
    path("listPacks/", views.listPackage.as_view() , name="listpacks"),
    path("sendPacks/", views.sendPackage , name="packs"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from account.models import User

# class marbot be viljegi haye maghalat va mosabeghat
class Article(models.Model):
	STATUS_CHOICES = (
		('d', 'پیش‌نویس'),		 # draft
		('p', "منتشر شده"),		 # publish
		('i', "در حال بررسی"),	 # investigation
		('b', "برگشت داده شده"), # back
	)
 
	author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name="نویسنده")
	title = models.CharField(max_length=200, verbose_name="عنوان مقاله")
	slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس مقاله")
	category = models.CharField(max_length=50)
	description = models.TextField(verbose_name="محتوا")
	thumbnail = models.ImageField(upload_to="images", verbose_name="تصویر مقاله")
	publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")

	def __str__(self) :
		return self.slug

blog/views.py
from . import models
from django.shortcuts import render
from django.views.generic import ListView, DetailView
# class list kardan article
class ArticleListView(ListView):
    model = models.Article
    context_object_name = 'articles'
    template_name = 'blog/list.html'
    paginate_by = 4
    
    def get_queryset(self):
        return models.Article.objects.order_by('-updated', '-created').filter(status = 'p')

# class braye didan article
class ArticleDetailView(DetailView):
    model = models.Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'
    

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title style="font-family: 'Vazir';">وبلاگ خانه‌ هوشمند</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- fontawesome baraye yek seri icon- -->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- font haye google-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- include kardan file haye css (ke bootsrap ham darad) -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/font.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- ghesmate navbar-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <div style="margin-right: 90%;" class="collapse navbar-collapse" id="navbarResponsive">
                </div>
                <a style="direction: rtl; font-family: 'Vazir'; margin-right: 20%;" class="navbar-brand" href="{% url 'home:index' %}">خانه‌ی هوشمند</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                </button> 
            </div>
        </nav>
        <!-- ghesmate headere safhe-->
        <header class="masthead" style="background-image: url('{{ article.thumbnail.url }}')">
            <div style="margin-left: 20%;" class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div style="margin-left: 13%; color: black !important;" class="post-heading">
                            <h1 style="font-family: 'Vazir';">{{ article.title }}</h1>
                            <span style="direction: rtl; font-family: 'Vazir'; margin-right: 25%;" class="meta">
                                ارسال شده توسط:
                                <a style="color: black !important;">{{ article.author }}</a>
                                در {{ article.publish }}
                                <div><span style="margin-right: 40%; margin-top: 1%;" class="badge bg-danger" style="font-size: 14px;"> دسته‌بندی: {{ article.category }} </span></div>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- mohtaviat maghalat -->
        <article style="direction: rtl; font-family: 'Vazir';" class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {{ article.description }}
                    </div>
                </div>
            </div>
        </article>
        <!-- ghesmate Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- include kardan file haye javascript bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
        <!-- include kardan file javascript-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
</html>

blog/templates/blog/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Smart House</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- link kardan file haye css -->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/font.css' %}">
        
    </head>
    <body>
        <!-- ghesmate Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <div style="margin-right: 90%;" class="collapse navbar-collapse" id="navbarResponsive">
                </div>
                <a style="direction: rtl; font-family: 'Vazir'; margin-right: 20%; color: white !important;" class="navbar-brand" href="{% url 'home:index' %}">خانه‌‌ی هوشمند</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                </button>
            </div>
        </nav>
        <!-- ghesmate header safhe -->
        <header class="masthead" style=" background-image: url('{% static 'blog/img/Untitled.jpeg' %}')"> <!-- background-image: url('assets/img/home-bg.jpg') | background-color: #bcf5ff !important; -->
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <a href="{% url 'home:index' %}"><h1 style="font-family: 'Vazir'; color: white !important; white-space: nowrap; text-decoration: none;" >وبلاگ‌ خانه‌‌ی هوشمند</h1></a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- mohtaviat asli-->
        <div class="container px-4 px-lg-5" style="direction: rtl;">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- preview ye post ha-->
                    <div style="font-family: 'Vazir' !important; " class="row">
                        <div class="row">
                            {% for article in articles %}
                                    <div class="post-preview">
                                        <a href="{% url 'blog:detail' article.slug %}" style="font-family: 'Vazir';">
                                            <h2 class="post-title" style="font-family: 'Vazir';">{{ article.title }}</h2>
                                            <h3 class="post-subtitle" style="font-family: 'Vazir';">{{article.description| slice:":30" }}...</h3>
                                        </a>
                                        <p style="font-family: 'Vazir';" class="post-meta">
                                            نوشته شده توسط:
                                            <a href="{% url 'blog:detail' article.slug %}" style="font-family: 'Vazir';">{{ article.author.username }}</a>
                                            در {{ article.publish }}
                                        </p>
                                    </div><br><br>
                                    <hr class="my-4" /><br><br>
                                    {% empty %}
                                    <div style="font-family: 'Vazir' !important;direction: rtl;" class="alert alert-warning alert-dismissible fade show" role="alert">
                                        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffca2c}</style><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"/></svg>                                         هیچ موردی برای نمایش   <strong class="alert-link" >وجود ندارد.</strong> 
                                        <button style="margin-right: 90%;" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>                                    
                                {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ghesmate Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap file haye javascript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- file haye javascript-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>